# Copyright (C) 2025 Cory Jon Hollingsworth
#
# This file is part of Muscle Buddy.
#
# Muscle Buddy is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Muscle Buddy.  If not, see <https://www.gnu.org/licenses/>.
<ExerciseSelectorPopupWindow>:
    background_color: (1.5, 1.5, 1.5, 0.75)
    pos_hint: {'x': 0.025, 'bottom': 0.025}
    separator_height: 0
    size_hint: (0.95, 0.95)
    title: 'Select Exercise'
    title_align: 'center'
    title_size: window_height // 45
