# Copyright (C) 2025 Cory Jon Hollingsworth
#
# This file is part of Muscle Buddy.
#
# Muscle Buddy is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Muscle Buddy.  If not, see <https://www.gnu.org/licenses/>.
<LicenseLabel>:
    canvas.before:
        Color:
            rgba: (0.2, 0.2, 0.2, 1)
        Rectangle:
            pos: self.pos
            size: self.size
    size_hint_y: None
    height: self.texture_size[1]
    text_size: self.width, None
    font_size: window_height // 55
    text_color: 1, 1, 1, 1