# Copyright (C) 2025 Cory Jon Hollingsworth
#
# This file is part of Muscle Buddy.
#
# Muscle Buddy is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Muscle Buddy.  If not, see <https://www.gnu.org/licenses/>.
#:import os os

<Loading@BoxLayout>:
    id: loading_layout
    orientation: 'vertical'

    MDLabel:
        id: loading_label
        size_hint_y: 0.2
        text: 'LOADING...'
        halign: 'center'
        theme_text_color: 'Custom'
        text_color: 1, 1, 1, 1
        font_style: 'H5'

    AsyncImage:
        source: os.path.join('images', 'presplash.png')
        fit_mode: 'contain'
        mipmap: True
                        
