# Copyright (C) 2025 Cory Jon Hollingsworth
#
# This file is part of Muscle Buddy.
#
# Muscle Buddy is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Muscle Buddy.  If not, see <https://www.gnu.org/licenses/>.
<Timers>:
    orientation: 'vertical'
    FloatLayout:
        MDBoxLayout:
            orientation: 'vertical'
            halign: 'center'
            Label:
                text: root.local_time
                size_hint_y: 0.05
                halign: 'center'
                valign: 'top'
                font_size: window_height // 30
            Widget:
                size_hint_y: None
            Label:
                text: 'Timer'
                size_hint_y: 0.05
                halign: 'center'
                valign: 'top'
                font_size: window_height // 15
            GenericTimer:
                id: timer
                text: app.generic_timer
                size_hint_y: 0.1
                halign: 'center'
                valign: 'top'
                font_size: window_height // 10
                markup: True
            Widget:
                size_hint_y: 0.15
            Label:
                text: 'Stopwatch'
                size_hint_y: 0.05
                halign: 'center'
                valign: 'top'
                font_size: window_height // 15
            StopWatch:
                id: stopwatch
                text: app.generic_stopwatch
                size_hint_y: 0.1
                halign: 'center'
                valign: 'top'
                font_size: window_height // 10
                markup: True
            Widget:
                size_hint_y: None
                AnchorLayout:
        AnchorLayout:
            anchor_x: 'left'
            anchor_y: 'bottom'
            MDIconButton:
                id: workout_trainer_fast_nav_button_id
                icon: 'weight-lifter'
                icon_size: window_height // 19
                on_release: app.fast_nav('workout_trainer_id')
        AnchorLayout:
            id: keypad_button_container_id
            anchor_x: 'right'
            anchor_y: 'bottom'
        AnchorLayout:
            id: keypad_container_id
            anchor_x: 'center'
            anchor_y: 'bottom'
